name: AutoTool
version: ${version}
main: com.github.vanes430.autotool.AutoTool

# --- PERUBAHAN DI SINI ---
# Ubah dari 1.8 menjadi 1.13 atau lebih tinggi.
# Ini akan menonaktifkan remapping dari PaperMC yang menyebabkan error.
api-version: 1.13
# -------------------------

author: vanes430

commands:
  autotool:
    description: Toggles AutoTool feature or reloads the configuration.
    usage: /<command> [reload]
    permission: autotool.use

permissions:
  autotool.use:
    description: Allows using the /autotool command to toggle the feature.
    default: true
  autotool.reload:
    description: Allows using /autotool reload.
    default: op