name: AutoTool
version: '${project.version}'
main: com.github.vanes430.autotool.AutoTool
api-version: '1.13'
author: vanes430
description: Automatically change your item to what's best in your hotbar when breaking blocks.
commands:
  autotool:
    description: Toggle autotool.
    usage: /autotool
    permission: autotool.toggle